[package]
name = "schulte_table"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_embedded_assets = "0.11.0"
rand = "0.8.5"

[lib]
name = "schulte_table"
crate-type = ["staticlib", "cdylib"]
